# Generated by Django 6.0.5 on 2026-05-16 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperaturereading',
            name='device_key',
        ),
        migrations.AddField(
            model_name='temperaturereading',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device'),
            preserve_default=False,
        ),
    ]
